### ISSUE TITLE
The secondary tab cannot scroll properly due to fast scrolling

### ISSUE THREAD

**Issue by huangxianyu** [hgraceb/nested_scroll_views#12]
This demo is very good, but there is a small problem, fast scrolling, secondary tab can not scroll normally, will directly switch primary tab, how to avoid, thank you very much!

https://github.com/user-attachments/assets/8d3a0ba3-699f-449f-9d05-c9b1118a3ff7

**Comment by hgraceb** [comment]
Actually, it's the default behavior of flutter. You can see the same results if you nested some PageView replace of NestedPageView. So there is not a simple way to do what you want at this moment.
