### ISSUE TITLE
Supporting a callback when the page changes for NestedPageView

### ISSUE THREAD

**Issue by iamv4g** [hgraceb/nested_scroll_views#6]
Hi @hgraceb,

I'm very grateful for you creating this library. It helped me solve my nested PageView problems.

Would you consider supporting a callback when the page changes? (add an onPageChanging parameter or something similar.) 

This would help to prevent the widget tree from becoming too deep when having to add a `NotificationListener` as a parent above the `NestedPageView`.

**Comment by hgraceb** [comment]
Thanks! But that's how Flutter is designed. You can create a generic widget with `NotificationListener` to reach what you want.
